TestNuscenes: false # true or false

ModelConfig: ./src/bevdet/src/bevdet-tensorrt-cpp/cfgs/bevdet_lt_depth.yaml

N: 1
H: 360
W: 640
# cams: [CAM_FRONT_LEFT, CAM_FRONT, CAM_FRONT_RIGHT, CAM_BACK_LEFT, CAM_BACK, CAM_BACK_RIGHT]
# sample:
#     CAM_FRONT_LEFT: ../sample0/imgs/CAM_FRONT_LEFT.jpg
#     CAM_FRONT: ../sample0/imgs/CAM_FRONT.jpg
#     CAM_FRONT_RIGHT: ../sample0/imgs/CAM_FRONT_RIGHT.jpg
#     CAM_BACK_LEFT: ../sample0/imgs/CAM_BACK_LEFT.jpg
#     CAM_BACK: ../sample0/imgs/CAM_BACK.jpg
#     CAM_BACK_RIGHT: ../sample0/imgs/CAM_BACK_RIGHT.jpg

cams: [CAM_FRONT]
sample:
    CAM_FRONT: ./src/bevdet/src/bevdet-tensorrt-cpp/sample0/imgs/CAM_FRONT.jpg

CamConfig: ./src/bevdet/src/bevdet-tensorrt-cpp/sample0/sample0001.yaml
InputFile: ./src/bevdet/src/bevdet-tensorrt-cpp/sample0/0.pcd
OutputLidarBox: ./src/bevdet/src/bevdet-tensorrt-cpp/sample0/sample0_lidarbox.txt

ImgStageEngine: ./src/bevdet/src/bevdet-tensorrt-cpp/model/img_stage_lt_d_fp16.engine
BEVStageEngine: ./src/bevdet/src/bevdet-tensorrt-cpp/model/bev_stage_lt_d_fp16.engine


OutputDir: ./src/bevdet/src/bevdet-tensorrt-cpp/output/

LoadDim: 5
UseDim: 4

dataset_info: ./src/bevdet/src/bevdet-tensorrt-cpp/data/nuscenes/data_infos
